In [1]:
%pip install librosa

Requirement already satisfied: librosa in c:\users\robin\appdata\local\programs\python\python311\lib\site-packages (0.10.0.post2)
Requirement already satisfied: audioread>=2.1.9 in c:\users\robin\appdata\local\programs\python\python311\lib\site-packages (from librosa) (3.0.0)
Requirement already satisfied: numpy!=1.22.0,!=1.22.1,!=1.22.2,>=1.20.3 in c:\users\robin\appdata\local\programs\python\python311\lib\site-packages (from librosa) (1.23.5)
Requirement already satisfied: scipy>=1.2.0 in c:\users\robin\appdata\local\programs\python\python311\lib\site-packages (from librosa) (1.10.1)
Requirement already satisfied: scikit-learn>=0.20.0 in c:\users\robin\appdata\local\programs\python\python311\lib\site-packages (from librosa) (1.2.1)
Requirement already satisfied: joblib>=0.14 in c:\users\robin\appdata\local\programs\python\python311\lib\site-packages (from librosa) (1.2.0)
Requirement already satisfied: decorator>=4.3.0 in c:\users\robin\appdata\roaming\python\python311\site-packages (from librosa) (5.1.1)
Requirement already satisfied: numba>=0.51.0 in c:\users\robin\appdata\local\programs\python\python311\lib\site-packages (from librosa) (0.57.0)
Requirement already satisfied: soundfile>=0.12.1 in c:\users\robin\appdata\local\programs\python\python311\lib\site-packages (from librosa) (0.12.1)
Requirement already satisfied: pooch<1.7,>=1.0 in c:\users\robin\appdata\local\programs\python\python311\lib\site-packages (from librosa) (1.6.0)
Requirement already satisfied: soxr>=0.3.2 in c:\users\robin\appdata\local\programs\python\python311\lib\site-packages (from librosa) (0.3.5)
Requirement already satisfied: typing-extensions>=4.1.1 in c:\users\robin\appdata\local\programs\python\python311\lib\site-packages (from librosa) (4.5.0)
Requirement already satisfied: lazy-loader>=0.1 in c:\users\robin\appdata\local\programs\python\python311\lib\site-packages (from librosa) (0.2)
Requirement already satisfied: msgpack>=1.0 in c:\users\robin\appdata\local\programs\python\python311\lib\site-packages (from librosa) (1.0.5)
Requirement already satisfied: llvmlite<0.41,>=0.40.0dev0 in c:\users\robin\appdata\local\programs\python\python311\lib\site-packages (from numba>=0.51.0->librosa) (0.40.0)
Requirement already satisfied: appdirs>=1.3.0 in c:\users\robin\appdata\local\programs\python\python311\lib\site-packages (from pooch<1.7,>=1.0->librosa) (1.4.4)
Requirement already satisfied: packaging>=20.0 in c:\users\robin\appdata\roaming\python\python311\site-packages (from pooch<1.7,>=1.0->librosa) (22.0)
Requirement already satisfied: requests>=2.19.0 in c:\users\robin\appdata\local\programs\python\python311\lib\site-packages (from pooch<1.7,>=1.0->librosa) (2.28.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\robin\appdata\local\programs\python\python311\lib\site-packages (from scikit-learn>=0.20.0->librosa) (3.1.0)
Requirement already satisfied: cffi>=1.0 in c:\users\robin\appdata\local\programs\python\python311\lib\site-packages (from soundfile>=0.12.1->librosa) (1.15.1)
Requirement already satisfied: pycparser in c:\users\robin\appdata\local\programs\python\python311\lib\site-packages (from cffi>=1.0->soundfile>=0.12.1->librosa) (2.21)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\robin\appdata\local\programs\python\python311\lib\site-packages (from requests>=2.19.0->pooch<1.7,>=1.0->librosa) (2.1.1)
Requirement already satisfied: idna<4,>=2.5 in c:\users\robin\appdata\local\programs\python\python311\lib\site-packages (from requests>=2.19.0->pooch<1.7,>=1.0->librosa) (3.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\robin\appdata\local\programs\python\python311\lib\site-packages (from requests>=2.19.0->pooch<1.7,>=1.0->librosa) (1.26.14)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\robin\appdata\local\programs\python\python311\lib\site-packages (from requests>=2.19.0->pooch<1.7,>=1.0->librosa) (2022.12.7)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip available: 22.3.1 -> 23.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
%pip install resampy

Requirement already satisfied: resampy in c:\users\robin\appdata\local\programs\python\python311\lib\site-packages (0.4.2)
Requirement already satisfied: numpy>=1.17 in c:\users\robin\appdata\local\programs\python\python311\lib\site-packages (from resampy) (1.23.5)
Requirement already satisfied: numba>=0.53 in c:\users\robin\appdata\local\programs\python\python311\lib\site-packages (from resampy) (0.57.0)
Requirement already satisfied: llvmlite<0.41,>=0.40.0dev0 in c:\users\robin\appdata\local\programs\python\python311\lib\site-packages (from numba>=0.53->resampy) (0.40.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip available: 22.3.1 -> 23.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
%pip install python_speech_features

Requirement already satisfied: python_speech_features in c:\users\robin\appdata\local\programs\python\python311\lib\site-packages (0.6)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip available: 22.3.1 -> 23.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [4]:
%pip install tensorflow

Requirement already satisfied: tensorflow in c:\users\robin\appdata\local\programs\python\python311\lib\site-packages (2.12.0)
Requirement already satisfied: tensorflow-intel==2.12.0 in c:\users\robin\appdata\local\programs\python\python311\lib\site-packages (from tensorflow) (2.12.0)
Requirement already satisfied: absl-py>=1.0.0 in c:\users\robin\appdata\local\programs\python\python311\lib\site-packages (from tensorflow-intel==2.12.0->tensorflow) (1.4.0)
Requirement already satisfied: astunparse>=1.6.0 in c:\users\robin\appdata\local\programs\python\python311\lib\site-packages (from tensorflow-intel==2.12.0->tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=2.0 in c:\users\robin\appdata\local\programs\python\python311\lib\site-packages (from tensorflow-intel==2.12.0->tensorflow) (23.3.3)
Requirement already satisfied: gast<=0.4.0,>=0.2.1 in c:\users\robin\appdata\local\programs\python\python311\lib\site-packages (from tensorflow-intel==2.12.0->tensorflow) (0.4.0)
Requirement already satisfied: google-pasta>=0.1.1 in c:\users\robin\appdata\local\programs\python\python311\lib\site-packages (from tensorflow-intel==2.12.0->tensorflow) (0.2.0)
Requirement already satisfied: h5py>=2.9.0 in c:\users\robin\appdata\local\programs\python\python311\lib\site-packages (from tensorflow-intel==2.12.0->tensorflow) (3.8.0)
Requirement already satisfied: jax>=0.3.15 in c:\users\robin\appdata\local\programs\python\python311\lib\site-packages (from tensorflow-intel==2.12.0->tensorflow) (0.4.8)
Requirement already satisfied: libclang>=13.0.0 in c:\users\robin\appdata\local\programs\python\python311\lib\site-packages (from tensorflow-intel==2.12.0->tensorflow) (16.0.0)
Requirement already satisfied: numpy<1.24,>=1.22 in c:\users\robin\appdata\local\programs\python\python311\lib\site-packages (from tensorflow-intel==2.12.0->tensorflow) (1.23.5)
Requirement already satisfied: opt-einsum>=2.3.2 in c:\users\robin\appdata\local\programs\python\python311\lib\site-packages (from tensorflow-intel==2.12.0->tensorflow) (3.3.0)
Requirement already satisfied: packaging in c:\users\robin\appdata\roaming\python\python311\site-packages (from tensorflow-intel==2.12.0->tensorflow) (22.0)
Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.20.3 in c:\users\robin\appdata\local\programs\python\python311\lib\site-packages (from tensorflow-intel==2.12.0->tensorflow) (4.22.3)
Requirement already satisfied: setuptools in c:\users\robin\appdata\local\programs\python\python311\lib\site-packages (from tensorflow-intel==2.12.0->tensorflow) (65.5.0)
Requirement already satisfied: six>=1.12.0 in c:\users\robin\appdata\roaming\python\python311\site-packages (from tensorflow-intel==2.12.0->tensorflow) (1.16.0)
Requirement already satisfied: termcolor>=1.1.0 in c:\users\robin\appdata\local\programs\python\python311\lib\site-packages (from tensorflow-intel==2.12.0->tensorflow) (2.3.0)
Requirement already satisfied: typing-extensions>=3.6.6 in c:\users\robin\appdata\local\programs\python\python311\lib\site-packages (from tensorflow-intel==2.12.0->tensorflow) (4.5.0)
Requirement already satisfied: wrapt<1.15,>=1.11.0 in c:\users\robin\appdata\local\programs\python\python311\lib\site-packages (from tensorflow-intel==2.12.0->tensorflow) (1.14.1)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in c:\users\robin\appdata\local\programs\python\python311\lib\site-packages (from tensorflow-intel==2.12.0->tensorflow) (1.54.0)
Requirement already satisfied: tensorboard<2.13,>=2.12 in c:\users\robin\appdata\local\programs\python\python311\lib\site-packages (from tensorflow-intel==2.12.0->tensorflow) (2.12.3)
Requirement already satisfied: tensorflow-estimator<2.13,>=2.12.0 in c:\users\robin\appdata\local\programs\python\python311\lib\site-packages (from tensorflow-intel==2.12.0->tensorflow) (2.12.0)
Requirement already satisfied: keras<2.13,>=2.12.0 in c:\users\robin\appdata\local\programs\python\python311\lib\site-packages (from tensorflow-intel==2.12.0->tensorflow) (2.12.0)
Requirement already satisfied: tensorflow-io-gcs-filesystem>=0.23.1 in c:\users\robin\appdata\local\programs\python\python311\lib\site-packages (from tensorflow-intel==2.12.0->tensorflow) (0.31.0)
Requirement already satisfied: wheel<1.0,>=0.23.0 in c:\users\robin\appdata\local\programs\python\python311\lib\site-packages (from astunparse>=1.6.0->tensorflow-intel==2.12.0->tensorflow) (0.40.0)
Requirement already satisfied: ml-dtypes>=0.0.3 in c:\users\robin\appdata\local\programs\python\python311\lib\site-packages (from jax>=0.3.15->tensorflow-intel==2.12.0->tensorflow) (0.1.0)
Requirement already satisfied: scipy>=1.7 in c:\users\robin\appdata\local\programs\python\python311\lib\site-packages (from jax>=0.3.15->tensorflow-intel==2.12.0->tensorflow) (1.10.1)
Requirement already satisfied: google-auth<3,>=1.6.3 in c:\users\robin\appdata\local\programs\python\python311\lib\site-packages (from tensorboard<2.13,>=2.12->tensorflow-intel==2.12.0->tensorflow) (2.17.3)
Requirement already satisfied: google-auth-oauthlib<1.1,>=0.5 in c:\users\robin\appdata\local\programs\python\python311\lib\site-packages (from tensorboard<2.13,>=2.12->tensorflow-intel==2.12.0->tensorflow) (1.0.0)
Requirement already satisfied: markdown>=2.6.8 in c:\users\robin\appdata\local\programs\python\python311\lib\site-packages (from tensorboard<2.13,>=2.12->tensorflow-intel==2.12.0->tensorflow) (3.4.3)
Requirement already satisfied: requests<3,>=2.21.0 in c:\users\robin\appdata\local\programs\python\python311\lib\site-packages (from tensorboard<2.13,>=2.12->tensorflow-intel==2.12.0->tensorflow) (2.28.2)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in c:\users\robin\appdata\local\programs\python\python311\lib\site-packages (from tensorboard<2.13,>=2.12->tensorflow-intel==2.12.0->tensorflow) (0.7.0)
Requirement already satisfied: werkzeug>=1.0.1 in c:\users\robin\appdata\local\programs\python\python311\lib\site-packages (from tensorboard<2.13,>=2.12->tensorflow-intel==2.12.0->tensorflow) (2.3.3)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in c:\users\robin\appdata\local\programs\python\python311\lib\site-packages (from google-auth<3,>=1.6.3->tensorboard<2.13,>=2.12->tensorflow-intel==2.12.0->tensorflow) (5.3.0)
Requirement already satisfied: pyasn1-modules>=0.2.1 in c:\users\robin\appdata\local\programs\python\python311\lib\site-packages (from google-auth<3,>=1.6.3->tensorboard<2.13,>=2.12->tensorflow-intel==2.12.0->tensorflow) (0.3.0)
Requirement already satisfied: rsa<5,>=3.1.4 in c:\users\robin\appdata\local\programs\python\python311\lib\site-packages (from google-auth<3,>=1.6.3->tensorboard<2.13,>=2.12->tensorflow-intel==2.12.0->tensorflow) (4.9)
Requirement already satisfied: requests-oauthlib>=0.7.0 in c:\users\robin\appdata\local\programs\python\python311\lib\site-packages (from google-auth-oauthlib<1.1,>=0.5->tensorboard<2.13,>=2.12->tensorflow-intel==2.12.0->tensorflow) (1.3.1)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\robin\appdata\local\programs\python\python311\lib\site-packages (from requests<3,>=2.21.0->tensorboard<2.13,>=2.12->tensorflow-intel==2.12.0->tensorflow) (2.1.1)
Requirement already satisfied: idna<4,>=2.5 in c:\users\robin\appdata\local\programs\python\python311\lib\site-packages (from requests<3,>=2.21.0->tensorboard<2.13,>=2.12->tensorflow-intel==2.12.0->tensorflow) (3.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\robin\appdata\local\programs\python\python311\lib\site-packages (from requests<3,>=2.21.0->tensorboard<2.13,>=2.12->tensorflow-intel==2.12.0->tensorflow) (1.26.14)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\robin\appdata\local\programs\python\python311\lib\site-packages (from requests<3,>=2.21.0->tensorboard<2.13,>=2.12->tensorflow-intel==2.12.0->tensorflow) (2022.12.7)
Requirement already satisfied: MarkupSafe>=2.1.1 in c:\users\robin\appdata\local\programs\python\python311\lib\site-packages (from werkzeug>=1.0.1->tensorboard<2.13,>=2.12->tensorflow-intel==2.12.0->tensorflow) (2.1.2)
Requirement already satisfied: pyasn1<0.6.0,>=0.4.6 in c:\users\robin\appdata\local\programs\python\python311\lib\site-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard<2.13,>=2.12->tensorflow-intel==2.12.0->tensorflow) (0.5.0)
Requirement already satisfied: oauthlib>=3.0.0 in c:\users\robin\appdata\local\programs\python\python311\lib\site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<1.1,>=0.5->tensorboard<2.13,>=2.12->tensorflow-intel==2.12.0->tensorflow) (3.2.2)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip available: 22.3.1 -> 23.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [5]:
import os
from tqdm import tqdm
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy.io import wavfile
from python_speech_features import mfcc, logfbank
import resampy

In [6]:
import matplotlib.pyplot as plt
%matplotlib inline

In [7]:
import IPython.display as ipd
import librosa
import librosa.display

In [8]:
!dir

 Volume in drive G is Local Disk
 Volume Serial Number is D6AB-2C6D

 Directory of g:\Downloads\PGDBA\Project audi_classif

15-05-2023  22:37    <DIR>          .
14-05-2023  20:17    <DIR>          ..
20-05-2023  19:01            78,137 audi copy.ipynb
15-05-2023  22:04            72,033 audi.ipynb
15-05-2023  22:01                 0 audi2.ipynb
14-05-2023  20:17    <DIR>          PGDBA-Project-20230514T144324Z-001
14-05-2023  20:15        98,800,322 PGDBA-Project-20230514T144324Z-001.zip
15-05-2023  21:40    <DIR>          saved_models
15-05-2023  14:11    <DIR>          UrbanSound8K
15-05-2023  01:23     6,023,741,708 UrbanSound8K.tar.gz
               5 File(s)  6,122,692,200 bytes
               5 Dir(s)  222,612,131,840 bytes free

In [9]:
import pandas as pd

metadata=pd.read_csv('G:/Downloads/PGDBA/Project audi_classif/UrbanSound8K/UrbanSound8K/metadata/UrbanSound8K.csv')
metadata.head(10)

,slice_file_name,fsID,start,end,salience,fold,classID,class
0,100032-3-0-0.wav,100032,0.000000,0.317551,1,5,3,dog_bark
1,100263-2-0-117.wav,100263,58.500000,62.500000,1,5,2,children_playing
2,100263-2-0-121.wav,100263,60.500000,64.500000,1,5,2,children_playing
3,100263-2-0-126.wav,100263,63.000000,67.000000,1,5,2,children_playing
4,100263-2-0-137.wav,100263,68.500000,72.500000,1,5,2,children_playing
5,100263-2-0-143.wav,100263,71.500000,75.500000,1,5,2,children_playing
6,100263-2-0-161.wav,100263,80.500000,84.500000,1,5,2,children_playing
7,100263-2-0-3.wav,100263,1.500000,5.500000,1,5,2,children_playing
8,100263-2-0-36.wav,100263,18.000000,22.000000,1,5,2,children_playing
9,100648-1-0-0.wav,100648,4.823402,5.471927,2,10,1,car_horn

In [10]:
### Check whether the dataset is imbalanced
metadata['class'].value_counts()

dog_bark            1000
children_playing    1000
air_conditioner     1000
street_music        1000
engine_idling       1000
jackhammer          1000
drilling            1000
siren                929
car_horn             429
gun_shot             374
Name: class, dtype: int64

In [11]:
#### Extracting MFCC's For every audio file
import pandas as pd
import os
import librosa

audio_dataset_path='G:/Downloads/PGDBA/Project audi_classif/UrbanSound8K/UrbanSound8K/audio'

In [12]:
def features_extractor(file):
    audio, sample_rate = librosa.load(file_name, res_type='kaiser_fast') 
    mfccs_features = librosa.feature.mfcc(y=audio, sr=sample_rate, n_mfcc=40)
    mfccs_scaled_features = np.mean(mfccs_features.T,axis=0)
    
    return mfccs_scaled_features

In [13]:
import numpy as np
from tqdm import tqdm
### Now we iterate through every audio file and extract features 
### using Mel-Frequency Cepstral Coefficients
extracted_features=[]
for index_num,row in tqdm(metadata.iterrows()):
    file_name = os.path.join(os.path.abspath(audio_dataset_path),'fold'+str(row["fold"])+'/',str(row["slice_file_name"]))
    final_class_labels=row["class"]
    data=features_extractor(file_name)
    extracted_features.append([data,final_class_labels])

3555it [05:05, 13.05it/s]c:\Users\robin\AppData\Local\Programs\Python\Python311\Lib\site-packages\librosa\core\spectrum.py:256: UserWarning: n_fft=2048 is too large for input signal of length=1323
  warnings.warn(
8326it [11:34, 12.13it/s]c:\Users\robin\AppData\Local\Programs\Python\Python311\Lib\site-packages\librosa\core\spectrum.py:256: UserWarning: n_fft=2048 is too large for input signal of length=1103
  warnings.warn(
8328it [11:35, 11.97it/s]c:\Users\robin\AppData\Local\Programs\Python\Python311\Lib\site-packages\librosa\core\spectrum.py:256: UserWarning: n_fft=2048 is too large for input signal of length=1523
  warnings.warn(
8732it [12:05, 12.04it/s]

In [14]:
### converting extracted_features to Pandas dataframe
extracted_features_df=pd.DataFrame(extracted_features,columns=['feature','class'])
extracted_features_df.head()

                                             feature             class
0  [-217.35526, 70.22338, -130.38527, -53.282898,...          dog_bark
1  [-424.09818, 109.34077, -52.919525, 60.86475, ...  children_playing
2  [-458.79114, 121.38419, -46.52066, 52.00812, -...  children_playing
3  [-413.89984, 101.66373, -35.42945, 53.036354, ...  children_playing
4  [-446.60352, 113.68541, -52.402214, 60.302044,...  children_playing

In [15]:
### Split the dataset into independent and dependent dataset
X=np.array(extracted_features_df['feature'].tolist())
y=np.array(extracted_features_df['class'].tolist())

In [16]:
X.shape

(8732, 40)

In [17]:
y

array(['dog_bark', 'children_playing', 'children_playing', ...,
       'car_horn', 'car_horn', 'car_horn'], dtype='<U16')

In [18]:
### Label Encoding
y=np.array(pd.get_dummies(y))

In [19]:
y.shape

(8732, 10)

In [20]:
### Train Test Split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=41)

In [21]:
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

(6985, 40) (1747, 40) (6985, 10) (1747, 10)

In [22]:
import tensorflow as tf

In [23]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Dropout,Activation,Flatten
from tensorflow.keras.optimizers import Adam
from sklearn import metrics

In [24]:
### No of classes
num_labels=y.shape[1]
num_labels

10

In [25]:
model=Sequential()
###first layer
model.add(Dense(100,input_shape=(40,)))
model.add(Activation('relu'))
model.add(Dropout(0.5))
###second layer
model.add(Dense(200))
model.add(Activation('relu'))
model.add(Dropout(0.5))
###third layer
model.add(Dense(100))
model.add(Activation('relu'))
model.add(Dropout(0.5))

###final layer
model.add(Dense(num_labels))
model.add(Activation('softmax'))

In [26]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 100)               4100

 activation (Activation)     (None, 100)               0

 dropout (Dropout)           (None, 100)               0

 dense_1 (Dense)             (None, 200)               20200

 activation_1 (Activation)   (None, 200)               0

 dropout_1 (Dropout)         (None, 200)               0

 dense_2 (Dense)             (None, 100)               20100

 activation_2 (Activation)   (None, 100)               0

 dropout_2 (Dropout)         (None, 100)               0

 dense_3 (Dense)             (None, 10)                1010

 activation_3 (Activation)   (None, 10)                0

=================================================================
Total params: 45,410
Trainable params: 45,410
Non-trainable params: 0
_________________________________________________________________

In [27]:
model.compile(loss='categorical_crossentropy',metrics=['accuracy'],optimizer='adam')

In [28]:
## Training the model
from tensorflow.keras.callbacks import ModelCheckpoint
from datetime import datetime 

num_epochs = 100
num_batch_size = 32

checkpointer = ModelCheckpoint(filepath='saved_models/audio_classification.hdf5', 
                               verbose=1, save_best_only=True)
start = datetime.now()

model.fit(X_train, y_train, batch_size=num_batch_size, epochs=num_epochs, validation_data=(X_test, y_test), callbacks=[checkpointer], verbose=1)


duration = datetime.now() - start
print("Training completed in time: ", duration)

Epoch 1/100
210/219 [===========================>..] - ETA: 0s - loss: 11.2849 - accuracy: 0.1179
Epoch 1: val_loss improved from inf to 2.29004, saving model to saved_models\audio_classification.hdf5
219/219 [==============================] - 2s 3ms/step - loss: 10.9692 - accuracy: 0.1181 - val_loss: 2.2900 - val_accuracy: 0.1265
Epoch 2/100
185/219 [========================>.....] - ETA: 0s - loss: 2.5801 - accuracy: 0.1236
Epoch 2: val_loss improved from 2.29004 to 2.27787, saving model to saved_models\audio_classification.hdf5
219/219 [==============================] - 0s 2ms/step - loss: 2.5524 - accuracy: 0.1247 - val_loss: 2.2779 - val_accuracy: 0.1231
Epoch 3/100
215/219 [============================>.] - ETA: 0s - loss: 2.3418 - accuracy: 0.1193
Epoch 3: val_loss improved from 2.27787 to 2.24019, saving model to saved_models\audio_classification.hdf5
219/219 [==============================] - 0s 2ms/step - loss: 2.3402 - accuracy: 0.1188 - val_loss: 2.2402 - val_accuracy: 0.1322
Epoch 4/100
173/219 [======================>.......] - ETA: 0s - loss: 2.2698 - accuracy: 0.1451
Epoch 4: val_loss improved from 2.24019 to 2.14387, saving model to saved_models\audio_classification.hdf5
219/219 [==============================] - 0s 2ms/step - loss: 2.2586 - accuracy: 0.1483 - val_loss: 2.1439 - val_accuracy: 0.1706
Epoch 5/100
217/219 [============================>.] - ETA: 0s - loss: 2.2000 - accuracy: 0.1679
Epoch 5: val_loss improved from 2.14387 to 2.12200, saving model to saved_models\audio_classification.hdf5
219/219 [==============================] - 0s 2ms/step - loss: 2.2000 - accuracy: 0.1681 - val_loss: 2.1220 - val_accuracy: 0.1895
Epoch 6/100
210/219 [===========================>..] - ETA: 0s - loss: 2.1684 - accuracy: 0.1750
Epoch 6: val_loss improved from 2.12200 to 2.09528, saving model to saved_models\audio_classification.hdf5
219/219 [==============================] - 0s 2ms/step - loss: 2.1700 - accuracy: 0.1737 - val_loss: 2.0953 - val_accuracy: 0.1757
Epoch 7/100
214/219 [============================>.] - ETA: 0s - loss: 2.1388 - accuracy: 0.1818
Epoch 7: val_loss improved from 2.09528 to 2.08281, saving model to saved_models\audio_classification.hdf5
219/219 [==============================] - 0s 2ms/step - loss: 2.1399 - accuracy: 0.1820 - val_loss: 2.0828 - val_accuracy: 0.2072
Epoch 8/100
182/219 [=======================>......] - ETA: 0s - loss: 2.1158 - accuracy: 0.1942
Epoch 8: val_loss improved from 2.08281 to 2.01817, saving model to saved_models\audio_classification.hdf5
219/219 [==============================] - 0s 2ms/step - loss: 2.1204 - accuracy: 0.1926 - val_loss: 2.0182 - val_accuracy: 0.2301
Epoch 9/100
187/219 [========================>.....] - ETA: 0s - loss: 2.0716 - accuracy: 0.2218
Epoch 9: val_loss improved from 2.01817 to 1.92992, saving model to saved_models\audio_classification.hdf5
219/219 [==============================] - 0s 2ms/step - loss: 2.0678 - accuracy: 0.2220 - val_loss: 1.9299 - val_accuracy: 0.2805
Epoch 10/100
209/219 [===========================>..] - ETA: 0s - loss: 2.0276 - accuracy: 0.2327
Epoch 10: val_loss improved from 1.92992 to 1.91105, saving model to saved_models\audio_classification.hdf5
219/219 [==============================] - 1s 7ms/step - loss: 2.0294 - accuracy: 0.2339 - val_loss: 1.9110 - val_accuracy: 0.3114
Epoch 11/100
207/219 [===========================>..] - ETA: 0s - loss: 2.0039 - accuracy: 0.2530
Epoch 11: val_loss improved from 1.91105 to 1.87714, saving model to saved_models\audio_classification.hdf5
219/219 [==============================] - 1s 2ms/step - loss: 2.0000 - accuracy: 0.2520 - val_loss: 1.8771 - val_accuracy: 0.3326
Epoch 12/100
175/219 [======================>.......] - ETA: 0s - loss: 1.9589 - accuracy: 0.2559
Epoch 12: val_loss improved from 1.87714 to 1.84135, saving model to saved_models\audio_classification.hdf5
219/219 [==============================] - 0s 2ms/step - loss: 1.9614 - accuracy: 0.2581 - val_loss: 1.8413 - val_accuracy: 0.3480
Epoch 13/100
174/219 [======================>.......] - ETA: 0s - loss: 1.9435 - accuracy: 0.2662
Epoch 13: val_loss improved from 1.84135 to 1.80919, saving model to saved_models\audio_classification.hdf5
219/219 [==============================] - 0s 2ms/step - loss: 1.9449 - accuracy: 0.2694 - val_loss: 1.8092 - val_accuracy: 0.3703
Epoch 14/100
218/219 [============================>.] - ETA: 0s - loss: 1.8921 - accuracy: 0.2946
Epoch 14: val_loss improved from 1.80919 to 1.76170, saving model to saved_models\audio_classification.hdf5
219/219 [==============================] - 1s 3ms/step - loss: 1.8923 - accuracy: 0.2945 - val_loss: 1.7617 - val_accuracy: 0.4322
Epoch 15/100
211/219 [===========================>..] - ETA: 0s - loss: 1.8509 - accuracy: 0.3190
Epoch 15: val_loss improved from 1.76170 to 1.69880, saving model to saved_models\audio_classification.hdf5
219/219 [==============================] - 0s 2ms/step - loss: 1.8510 - accuracy: 0.3177 - val_loss: 1.6988 - val_accuracy: 0.4413
Epoch 16/100
179/219 [=======================>......] - ETA: 0s - loss: 1.7764 - accuracy: 0.3514
Epoch 16: val_loss improved from 1.69880 to 1.62654, saving model to saved_models\audio_classification.hdf5
219/219 [==============================] - 1s 3ms/step - loss: 1.7736 - accuracy: 0.3535 - val_loss: 1.6265 - val_accuracy: 0.4717
Epoch 17/100
213/219 [============================>.] - ETA: 0s - loss: 1.7476 - accuracy: 0.3621
Epoch 17: val_loss improved from 1.62654 to 1.57912, saving model to saved_models\audio_classification.hdf5
219/219 [==============================] - 2s 10ms/step - loss: 1.7435 - accuracy: 0.3626 - val_loss: 1.5791 - val_accuracy: 0.4991
Epoch 18/100
176/219 [=======================>......] - ETA: 0s - loss: 1.6909 - accuracy: 0.3812
Epoch 18: val_loss improved from 1.57912 to 1.52050, saving model to saved_models\audio_classification.hdf5
219/219 [==============================] - 0s 2ms/step - loss: 1.6876 - accuracy: 0.3883 - val_loss: 1.5205 - val_accuracy: 0.5226
Epoch 19/100
215/219 [============================>.] - ETA: 0s - loss: 1.6203 - accuracy: 0.4049
Epoch 19: val_loss improved from 1.52050 to 1.46795, saving model to saved_models\audio_classification.hdf5
219/219 [==============================] - 0s 2ms/step - loss: 1.6182 - accuracy: 0.4062 - val_loss: 1.4679 - val_accuracy: 0.5352
Epoch 20/100
219/219 [==============================] - ETA: 0s - loss: 1.6228 - accuracy: 0.4172
Epoch 20: val_loss improved from 1.46795 to 1.43640, saving model to saved_models\audio_classification.hdf5
219/219 [==============================] - 0s 2ms/step - loss: 1.6228 - accuracy: 0.4172 - val_loss: 1.4364 - val_accuracy: 0.5369
Epoch 21/100
209/219 [===========================>..] - ETA: 0s - loss: 1.5527 - accuracy: 0.4415
Epoch 21: val_loss improved from 1.43640 to 1.42649, saving model to saved_models\audio_classification.hdf5
219/219 [==============================] - 0s 2ms/step - loss: 1.5528 - accuracy: 0.4428 - val_loss: 1.4265 - val_accuracy: 0.5266
Epoch 22/100
185/219 [========================>.....] - ETA: 0s - loss: 1.5450 - accuracy: 0.4444
Epoch 22: val_loss improved from 1.42649 to 1.38569, saving model to saved_models\audio_classification.hdf5
219/219 [==============================] - 0s 2ms/step - loss: 1.5479 - accuracy: 0.4418 - val_loss: 1.3857 - val_accuracy: 0.5701
Epoch 23/100
184/219 [========================>.....] - ETA: 0s - loss: 1.5018 - accuracy: 0.4723
Epoch 23: val_loss improved from 1.38569 to 1.35609, saving model to saved_models\audio_classification.hdf5
219/219 [==============================] - 0s 2ms/step - loss: 1.4981 - accuracy: 0.4733 - val_loss: 1.3561 - val_accuracy: 0.5690
Epoch 24/100
178/219 [=======================>......] - ETA: 0s - loss: 1.4888 - accuracy: 0.4682
Epoch 24: val_loss improved from 1.35609 to 1.35369, saving model to saved_models\audio_classification.hdf5
219/219 [==============================] - 0s 2ms/step - loss: 1.4925 - accuracy: 0.4667 - val_loss: 1.3537 - val_accuracy: 0.5787
Epoch 25/100
206/219 [===========================>..] - ETA: 0s - loss: 1.4720 - accuracy: 0.4774
Epoch 25: val_loss improved from 1.35369 to 1.32651, saving model to saved_models\audio_classification.hdf5
219/219 [==============================] - 0s 2ms/step - loss: 1.4744 - accuracy: 0.4789 - val_loss: 1.3265 - val_accuracy: 0.5781
Epoch 26/100
176/219 [=======================>......] - ETA: 0s - loss: 1.4345 - accuracy: 0.4885
Epoch 26: val_loss improved from 1.32651 to 1.29764, saving model to saved_models\audio_classification.hdf5
219/219 [==============================] - 0s 2ms/step - loss: 1.4291 - accuracy: 0.4923 - val_loss: 1.2976 - val_accuracy: 0.5879
Epoch 27/100
215/219 [============================>.] - ETA: 0s - loss: 1.4209 - accuracy: 0.5006
Epoch 27: val_loss did not improve from 1.29764
219/219 [==============================] - 0s 2ms/step - loss: 1.4210 - accuracy: 0.4992 - val_loss: 1.3030 - val_accuracy: 0.5947
Epoch 28/100
178/219 [=======================>......] - ETA: 0s - loss: 1.4236 - accuracy: 0.4984
Epoch 28: val_loss improved from 1.29764 to 1.29505, saving model to saved_models\audio_classification.hdf5
219/219 [==============================] - 0s 2ms/step - loss: 1.4173 - accuracy: 0.5012 - val_loss: 1.2951 - val_accuracy: 0.5867
Epoch 29/100
183/219 [========================>.....] - ETA: 0s - loss: 1.3940 - accuracy: 0.5142
Epoch 29: val_loss improved from 1.29505 to 1.26941, saving model to saved_models\audio_classification.hdf5
219/219 [==============================] - 0s 2ms/step - loss: 1.4010 - accuracy: 0.5115 - val_loss: 1.2694 - val_accuracy: 0.6027
Epoch 30/100
219/219 [==============================] - ETA: 0s - loss: 1.3661 - accuracy: 0.5254
Epoch 30: val_loss improved from 1.26941 to 1.24134, saving model to saved_models\audio_classification.hdf5
219/219 [==============================] - 0s 2ms/step - loss: 1.3661 - accuracy: 0.5254 - val_loss: 1.2413 - val_accuracy: 0.6193
Epoch 31/100
208/219 [===========================>..] - ETA: 0s - loss: 1.3595 - accuracy: 0.5204
Epoch 31: val_loss did not improve from 1.24134
219/219 [==============================] - 0s 2ms/step - loss: 1.3586 - accuracy: 0.5197 - val_loss: 1.2629 - val_accuracy: 0.5965
Epoch 32/100
180/219 [=======================>......] - ETA: 0s - loss: 1.3234 - accuracy: 0.5319
Epoch 32: val_loss improved from 1.24134 to 1.20371, saving model to saved_models\audio_classification.hdf5
219/219 [==============================] - 1s 4ms/step - loss: 1.3287 - accuracy: 0.5339 - val_loss: 1.2037 - val_accuracy: 0.6165
Epoch 33/100
206/219 [===========================>..] - ETA: 0s - loss: 1.3290 - accuracy: 0.5317
Epoch 33: val_loss improved from 1.20371 to 1.18817, saving model to saved_models\audio_classification.hdf5
219/219 [==============================] - 0s 2ms/step - loss: 1.3289 - accuracy: 0.5303 - val_loss: 1.1882 - val_accuracy: 0.6142
Epoch 34/100
212/219 [============================>.] - ETA: 0s - loss: 1.3252 - accuracy: 0.5454
Epoch 34: val_loss improved from 1.18817 to 1.18337, saving model to saved_models\audio_classification.hdf5
219/219 [==============================] - 0s 2ms/step - loss: 1.3255 - accuracy: 0.5442 - val_loss: 1.1834 - val_accuracy: 0.6262
Epoch 35/100
178/219 [=======================>......] - ETA: 0s - loss: 1.3078 - accuracy: 0.5448
Epoch 35: val_loss did not improve from 1.18337
219/219 [==============================] - 0s 2ms/step - loss: 1.3094 - accuracy: 0.5446 - val_loss: 1.1916 - val_accuracy: 0.6239
Epoch 36/100
212/219 [============================>.] - ETA: 0s - loss: 1.2921 - accuracy: 0.5545
Epoch 36: val_loss improved from 1.18337 to 1.17856, saving model to saved_models\audio_classification.hdf5
219/219 [==============================] - 1s 2ms/step - loss: 1.2889 - accuracy: 0.5553 - val_loss: 1.1786 - val_accuracy: 0.6279
Epoch 37/100
211/219 [===========================>..] - ETA: 0s - loss: 1.2828 - accuracy: 0.5572
Epoch 37: val_loss improved from 1.17856 to 1.14047, saving model to saved_models\audio_classification.hdf5
219/219 [==============================] - 0s 2ms/step - loss: 1.2820 - accuracy: 0.5569 - val_loss: 1.1405 - val_accuracy: 0.6319
Epoch 38/100
215/219 [============================>.] - ETA: 0s - loss: 1.2775 - accuracy: 0.5573
Epoch 38: val_loss improved from 1.14047 to 1.10431, saving model to saved_models\audio_classification.hdf5
219/219 [==============================] - 0s 2ms/step - loss: 1.2742 - accuracy: 0.5582 - val_loss: 1.1043 - val_accuracy: 0.6663
Epoch 39/100
181/219 [=======================>......] - ETA: 0s - loss: 1.2495 - accuracy: 0.5813
Epoch 39: val_loss did not improve from 1.10431
219/219 [==============================] - 0s 2ms/step - loss: 1.2520 - accuracy: 0.5784 - val_loss: 1.1215 - val_accuracy: 0.6422
Epoch 40/100
180/219 [=======================>......] - ETA: 0s - loss: 1.2267 - accuracy: 0.5748
Epoch 40: val_loss did not improve from 1.10431
219/219 [==============================] - 0s 2ms/step - loss: 1.2254 - accuracy: 0.5732 - val_loss: 1.1099 - val_accuracy: 0.6348
Epoch 41/100
215/219 [============================>.] - ETA: 0s - loss: 1.2419 - accuracy: 0.5706
Epoch 41: val_loss did not improve from 1.10431
219/219 [==============================] - 0s 2ms/step - loss: 1.2435 - accuracy: 0.5701 - val_loss: 1.1239 - val_accuracy: 0.6302
Epoch 42/100
181/219 [=======================>......] - ETA: 0s - loss: 1.2333 - accuracy: 0.5827
Epoch 42: val_loss improved from 1.10431 to 1.08446, saving model to saved_models\audio_classification.hdf5
219/219 [==============================] - 0s 2ms/step - loss: 1.2327 - accuracy: 0.5841 - val_loss: 1.0845 - val_accuracy: 0.6525
Epoch 43/100
183/219 [========================>.....] - ETA: 0s - loss: 1.2240 - accuracy: 0.5804
Epoch 43: val_loss did not improve from 1.08446
219/219 [==============================] - 0s 2ms/step - loss: 1.2156 - accuracy: 0.5834 - val_loss: 1.0877 - val_accuracy: 0.6560
Epoch 44/100
206/219 [===========================>..] - ETA: 0s - loss: 1.2155 - accuracy: 0.5900
Epoch 44: val_loss improved from 1.08446 to 1.08154, saving model to saved_models\audio_classification.hdf5
219/219 [==============================] - 0s 2ms/step - loss: 1.2142 - accuracy: 0.5910 - val_loss: 1.0815 - val_accuracy: 0.6474
Epoch 45/100
216/219 [============================>.] - ETA: 0s - loss: 1.1949 - accuracy: 0.5855
Epoch 45: val_loss improved from 1.08154 to 1.04210, saving model to saved_models\audio_classification.hdf5
219/219 [==============================] - 1s 3ms/step - loss: 1.1953 - accuracy: 0.5854 - val_loss: 1.0421 - val_accuracy: 0.6680
Epoch 46/100
214/219 [============================>.] - ETA: 0s - loss: 1.1835 - accuracy: 0.6059
Epoch 46: val_loss did not improve from 1.04210
219/219 [==============================] - 0s 2ms/step - loss: 1.1838 - accuracy: 0.6059 - val_loss: 1.0637 - val_accuracy: 0.6543
Epoch 47/100
181/219 [=======================>......] - ETA: 0s - loss: 1.1833 - accuracy: 0.5988
Epoch 47: val_loss did not improve from 1.04210
219/219 [==============================] - 0s 2ms/step - loss: 1.1792 - accuracy: 0.6017 - val_loss: 1.0596 - val_accuracy: 0.6583
Epoch 48/100
182/219 [=======================>......] - ETA: 0s - loss: 1.1755 - accuracy: 0.5939
Epoch 48: val_loss did not improve from 1.04210
219/219 [==============================] - 0s 2ms/step - loss: 1.1872 - accuracy: 0.5894 - val_loss: 1.0481 - val_accuracy: 0.6651
Epoch 49/100
209/219 [===========================>..] - ETA: 0s - loss: 1.1699 - accuracy: 0.5936
Epoch 49: val_loss improved from 1.04210 to 1.01947, saving model to saved_models\audio_classification.hdf5
219/219 [==============================] - 0s 2ms/step - loss: 1.1638 - accuracy: 0.5960 - val_loss: 1.0195 - val_accuracy: 0.6674
Epoch 50/100
175/219 [======================>.......] - ETA: 0s - loss: 1.1534 - accuracy: 0.6016
Epoch 50: val_loss did not improve from 1.01947
219/219 [==============================] - 0s 2ms/step - loss: 1.1539 - accuracy: 0.6049 - val_loss: 1.0322 - val_accuracy: 0.6560
Epoch 51/100
177/219 [=======================>......] - ETA: 0s - loss: 1.1558 - accuracy: 0.6059
Epoch 51: val_loss did not improve from 1.01947
219/219 [==============================] - 0s 2ms/step - loss: 1.1468 - accuracy: 0.6130 - val_loss: 1.0410 - val_accuracy: 0.6669
Epoch 52/100
200/219 [==========================>...] - ETA: 0s - loss: 1.1445 - accuracy: 0.6069
Epoch 52: val_loss improved from 1.01947 to 1.00546, saving model to saved_models\audio_classification.hdf5
219/219 [==============================] - 0s 2ms/step - loss: 1.1428 - accuracy: 0.6074 - val_loss: 1.0055 - val_accuracy: 0.6703
Epoch 53/100
181/219 [=======================>......] - ETA: 0s - loss: 1.1629 - accuracy: 0.6057
Epoch 53: val_loss did not improve from 1.00546
219/219 [==============================] - 0s 2ms/step - loss: 1.1677 - accuracy: 0.6042 - val_loss: 1.0322 - val_accuracy: 0.6720
Epoch 54/100
180/219 [=======================>......] - ETA: 0s - loss: 1.1493 - accuracy: 0.6054
Epoch 54: val_loss did not improve from 1.00546
219/219 [==============================] - 0s 2ms/step - loss: 1.1580 - accuracy: 0.6050 - val_loss: 1.0173 - val_accuracy: 0.6777
Epoch 55/100
176/219 [=======================>......] - ETA: 0s - loss: 1.1503 - accuracy: 0.6085
Epoch 55: val_loss did not improve from 1.00546
219/219 [==============================] - 0s 2ms/step - loss: 1.1581 - accuracy: 0.6064 - val_loss: 1.0112 - val_accuracy: 0.6846
Epoch 56/100
178/219 [=======================>......] - ETA: 0s - loss: 1.1301 - accuracy: 0.6183
Epoch 56: val_loss did not improve from 1.00546
219/219 [==============================] - 0s 2ms/step - loss: 1.1270 - accuracy: 0.6172 - val_loss: 1.0068 - val_accuracy: 0.6829
Epoch 57/100
178/219 [=======================>......] - ETA: 0s - loss: 1.1210 - accuracy: 0.6266
Epoch 57: val_loss did not improve from 1.00546
219/219 [==============================] - 0s 2ms/step - loss: 1.1257 - accuracy: 0.6251 - val_loss: 1.0115 - val_accuracy: 0.6720
Epoch 58/100
210/219 [===========================>..] - ETA: 0s - loss: 1.1213 - accuracy: 0.6173
Epoch 58: val_loss improved from 1.00546 to 0.97959, saving model to saved_models\audio_classification.hdf5
219/219 [==============================] - 0s 2ms/step - loss: 1.1213 - accuracy: 0.6162 - val_loss: 0.9796 - val_accuracy: 0.6703
Epoch 59/100
185/219 [========================>.....] - ETA: 0s - loss: 1.1050 - accuracy: 0.6162
Epoch 59: val_loss improved from 0.97959 to 0.97951, saving model to saved_models\audio_classification.hdf5
219/219 [==============================] - 0s 2ms/step - loss: 1.1110 - accuracy: 0.6168 - val_loss: 0.9795 - val_accuracy: 0.6772
Epoch 60/100
213/219 [============================>.] - ETA: 0s - loss: 1.0940 - accuracy: 0.6287
Epoch 60: val_loss improved from 0.97951 to 0.97864, saving model to saved_models\audio_classification.hdf5
219/219 [==============================] - 0s 2ms/step - loss: 1.0936 - accuracy: 0.6283 - val_loss: 0.9786 - val_accuracy: 0.6840
Epoch 61/100
217/219 [============================>.] - ETA: 0s - loss: 1.1033 - accuracy: 0.6233
Epoch 61: val_loss improved from 0.97864 to 0.96361, saving model to saved_models\audio_classification.hdf5
219/219 [==============================] - 0s 2ms/step - loss: 1.1055 - accuracy: 0.6226 - val_loss: 0.9636 - val_accuracy: 0.6915
Epoch 62/100
211/219 [===========================>..] - ETA: 0s - loss: 1.0914 - accuracy: 0.6278
Epoch 62: val_loss did not improve from 0.96361
219/219 [==============================] - 0s 2ms/step - loss: 1.0921 - accuracy: 0.6273 - val_loss: 0.9810 - val_accuracy: 0.6875
Epoch 63/100
212/219 [============================>.] - ETA: 0s - loss: 1.0951 - accuracy: 0.6266
Epoch 63: val_loss did not improve from 0.96361

In [29]:
test_accuracy=model.evaluate(X_test,y_test,verbose=0)
print(test_accuracy[1])

0.7240984439849854

In [30]:
predict_x=model.predict(X_test) 
classes_x=np.argmax(predict_x,axis=1)

55/55 [==============================] - 0s 578us/step

In [31]:
Y_preds = model.predict

In [32]:
filename="G:/Downloads/PGDBA/Project audi_classif/UrbanSound8K/UrbanSound8K/audio/fold2/4201-3-0-0.wav"
audio, sample_rate = librosa.load(filename, res_type='kaiser_fast') 
mfccs_features = librosa.feature.mfcc(y=audio, sr=sample_rate, n_mfcc=40)
mfccs_scaled_features = np.mean(mfccs_features.T,axis=0)

print(mfccs_scaled_features)
mfccs_scaled_features=mfccs_scaled_features.reshape(1,-1)
print(mfccs_scaled_features)
print(mfccs_scaled_features.shape)
predictions = (model.predict(X_test) > 0.5).astype("int32")
print(predictions)

[-2.33868500e+02  1.09056206e+02 -5.76975298e+00  1.65992870e+01
 -3.46133270e+01  2.37382679e+01 -4.64467859e+00  2.05459900e+01
  5.89833069e+00  9.75115967e+00  2.91429877e+00  1.32354250e+01
 -5.70944548e-02  1.65461006e+01 -5.76831675e+00  1.81195545e+01
  8.35268211e+00  2.35184250e+01  5.55858326e+00  5.03801680e+00
 -3.14165020e+00  8.64437008e+00 -1.87388659e+00  3.97579122e+00
  7.93383360e+00  1.31894326e+00 -7.96618462e+00  8.11050510e+00
  3.68082595e+00  1.63433247e+01  5.00579178e-01  7.89288104e-01
  1.75276268e+00 -3.20594263e+00  4.10227823e+00  2.05818057e+00
 -2.51707935e+00  3.52652121e+00  1.53722748e-01  1.73329616e+00]
[[-2.33868500e+02  1.09056206e+02 -5.76975298e+00  1.65992870e+01
  -3.46133270e+01  2.37382679e+01 -4.64467859e+00  2.05459900e+01
   5.89833069e+00  9.75115967e+00  2.91429877e+00  1.32354250e+01
  -5.70944548e-02  1.65461006e+01 -5.76831675e+00  1.81195545e+01
   8.35268211e+00  2.35184250e+01  5.55858326e+00  5.03801680e+00
  -3.14165020e+00  8.64437008e+00 -1.87388659e+00  3.97579122e+00
   7.93383360e+00  1.31894326e+00 -7.96618462e+00  8.11050510e+00
   3.68082595e+00  1.63433247e+01  5.00579178e-01  7.89288104e-01
   1.75276268e+00 -3.20594263e+00  4.10227823e+00  2.05818057e+00
  -2.51707935e+00  3.52652121e+00  1.53722748e-01  1.73329616e+00]]
(1, 40)
55/55 [==============================] - 0s 578us/step
[[0 1 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]